### ISSUE TITLE
multiple levels of (nested) properties

### ISSUE THREAD

**Issue by clintwood** [component/reactive#161]
@defunctzombie,

Couldn't [this baked in code / hack ;)](https://github.com/component/reactive/blob/master/lib/index.js#L77-L86) be moved to the default `Adapter.prototype.subscribe` implementation so that it does not interfere with custom Adapters implementations!

I'll be happy to do a PR if you agree this is right way to go...

BTW is this repo dying? I see very little activity!

**Comment by defunctzombie** [comment]
@clintwood I no longer do updates to this particular repo. I forked it here: https://github.com/notacatjs/dommit

The name was getting too confusing with all the other "react*" stuff out there. Would love to see a PR there!

**Comment by clintwood** [comment]
@defunctzombie, ok cool, thanks...
